version: "3"

services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      todo:
        aliases:
          - todo_db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    command: bash -c "alembic upgrade head && uvicorn app:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./backend/src:/code
    ports:
      - "8000:8000"
    env_file: .env
    networks:
      todo:
        aliases:
          - todo_backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    command: http-server dist
    volumes:
      - ./frontend:/code
    ports:
      - "80:8080"
    env_file: .env
    networks:
      todo:
        aliases:
          - todo_frontend

networks:
  todo:
    external: true

volumes:
  postgres_data:
